---
apiVersion: v1
kind: Service
metadata:
  name: ingress-envoy
  namespace: ingress-envoy
spec:
  selector:
    app: ingress-envoy
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-envoy
  namespace: ingress-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-envoy
  template:
    metadata:
      labels:
        app: ingress-envoy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.35.0
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - "--service-node ingress-envoy"
            - "--service-cluster ingress-envoy"
            - "--config-yaml"
            - |
              node:
                id: ingress-envoy
                cluster: ingress-envoy
              admin:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 15000
              dynamic_resources:
                ads_config:
                  api_type: GRPC
                  grpc_services:
                    - envoy_grpc:
                        cluster_name: xds_controller
                lds_config:
                  ads: {}
                cds_config:
                  ads: {}
              static_resources:
                clusters:
                  - name: xds_controller
                    type: STRICT_DNS
                    connect_timeout: 1s
                    http2_protocol_options: {}
                    load_assignment:
                      cluster_name: xds_controller
                      endpoints:
                        - lb_endpoints:
                            - endpoint:
                                address:
                                  socket_address:
                                    address: ingress-envoy-controller.ingress-envoy.svc.cluster.local
                                    port_value: 18000
          ports:
            - containerPort: 80 # proxy traffic
            - containerPort: 443 # proxy traffic
            - containerPort: 15000 # admin interface
          readinessProbe:
            httpGet:
              path: /ready
              port: 15000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /server_info
              port: 15000
            initialDelaySeconds: 10
            periodSeconds: 20